name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build_test:
    name: Build & Test App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install
          npm ci

      - name: Build & Test
        run: |
          npm run lint

  push_images:
    name: Push Images to DockerHub
    runs-on: ubuntu-latest
    needs: [build_test]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/express-demo:latest

      - name: Run Docker Image
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/express-demo:latest
          run: |
            echo "Running the Docker image"
            echo "Testing the Node.js app endpoints"
            echo ${{ steps.docker_build.outputs.digest }}
