
name: CI-CD

on: [push]

jobs:
  build_test:
    name: Build & Test App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]


    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
          npm ci
      - name: build & test
        run: |
          npm run lint